### ISSUE TITLE
EOFError

### ISSUE THREAD

**Issue by chantisnake** [WheatonCS/Lexos#208]
after uploading large file, and process that 

loading and saving filemanager takes a super long time even on the local box. 

Continue processing will get an EOFError

```
Traceback (most recent call last):
  File "/home/moses/anaconda/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/moses/anaconda/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/moses/anaconda/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moses/anaconda/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/moses/anaconda/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/moses/anaconda/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moses/anaconda/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/moses/anaconda/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/moses/PycharmProjects/LexosCulling/lexos.py", line 436, in kmeans
    fileManager = session_functions.loadFileManager()
  File "/home/moses/PycharmProjects/LexosCulling/helpers/session_functions.py", line 98, in loadFileManager
    fileManager = pickle.load(open(managerFilePath, 'rb'))
  File "/home/moses/anaconda/lib/python2.7/pickle.py", line 1378, in load
    return Unpickler(file).load()
  File "/home/moses/anaconda/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/home/moses/anaconda/lib/python2.7/pickle.py", line 880, in load_eof
    raise EOFError
EOFError
```

**Comment by chantisnake** [comment]
I think this is caused by storing DTM. This problem is more significant when you use Chinese and do not tokenize with gram

**Comment by JingxianL** [comment]
This has happened to me not only with tokenize but almost everywhere. And I couldn't recreate the problem, but it keeps coming up.

**Comment by chantisnake** [comment]
since the pickle is fast now and we haven't see this issue in a long time, I will close this
