### ISSUE TITLE
Uploading workspace.lexos produces 500 Internal Server error

### ISSUE THREAD

**Issue by evanlaferriere** [WheatonCS/Lexos#404]
### which option did I check
Download workspace/upload it
### which file did I use
GenAB, no scrubbing
### what the bug looks like
If you download a workspace file, go to upload and try to upload it, it will produce a localhost:5000 internal server error dialog box. If you drag it to the browse button, it will download the file again. It is catching for blank lexos files though. 
### error message if applicable 
127.0.0.1 - - [28/Jun/2016 11:42:08] "GET /reset HTTP/1.1" 302 -
127.0.0.1 - - [28/Jun/2016 11:42:08] "GET /upload HTTP/1.1" 200 -
127.0.0.1 - - [28/Jun/2016 11:42:10] "POST /upload HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/lexos/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/lexos/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/lexos/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/lexos/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lexos/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/lexos/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/lexos/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lexos/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lexos/Lexos/lexos.py", line 130, in upload
    fileManager.handleUploadWorkSpace()
  File "/home/lexos/Lexos/managers/file_manager.py", line 363, in handleUploadWorkSpace
    except (WindowsError, OSError) as e:
NameError: global name 'WindowsError' is not defined
127.0.0.1 - - [28/Jun/2016 11:44:24] "GET /viz HTTP/1.1" 200 -

### how to reproduce it
Dowload a lexos workspace and try to upload it
### workspace file
[workspace.zip](https://github.com/WheatonCS/Lexos/files/337439/workspace.zip)

**Comment by evanlaferriere** [comment]
Moses fixed this in about ten seconds, I'll push it
