### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by KiAlexander** [WheatonCS/Lexos#831]
After typing  python run.py, I encountered the following error:
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from lexos.application import run
  File "F:\test\PythonProject\Lexos\lexos\application.py", line 17, in <module>
    from lexos.views.dendrogram_view import dendrogram_blueprint
  File "F:\test\PythonProject\Lexos\lexos\views\dendrogram_view.py", line 5, in <module>
    from lexos.models.dendro_model import DendrogramModel
  File "F:\test\PythonProject\Lexos\lexos\models\dendro_model.py", line 19
    doc_term_matrix: pd.DataFrame
                   ^
SyntaxError: invalid syntax

**Comment by chantisnake** [comment]
Which version of python are you using, you need python 3.6+
